# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrderByColumn")

model_instance <- OrderByColumn$new()

test_that("field", {
  # tests for the property `field` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`field`, "EXPECTED_RESULT")
})

test_that("descending", {
  # tests for the property `descending` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`descending`, "EXPECTED_RESULT")
})
