# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GetValuesRequestBody")

model_instance <- GetValuesRequestBody$new()

test_that("filter", {
  # tests for the property `filter` (object)

  # uncomment below to test the property
  #expect_equal(model.instance$`filter`, "EXPECTED_RESULT")
})

test_that("order_by", {
  # tests for the property `order_by` (array[OrderByColumn])

  # uncomment below to test the property
  #expect_equal(model.instance$`order_by`, "EXPECTED_RESULT")
})

test_that("search", {
  # tests for the property `search` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`search`, "EXPECTED_RESULT")
})
