# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DefaultApi")

api_instance <- DefaultApi$new()

test_that("AddCollaboratorInstancesInstanceIdCollaboratorsAccountIdPut", {
  # tests for AddCollaboratorInstancesInstanceIdCollaboratorsAccountIdPut
  # base path: http://localhost
  # Add Collaborator
  # @param instance_id character
  # @param account_id character
  # @param schema_id character
  # @param role character  (optional)
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreateInstanceInstancesPut", {
  # tests for CreateInstanceInstancesPut
  # base path: http://localhost
  # Create Instance
  # @param name character
  # @param storage character  (optional)
  # @param schema_str character  (optional)
  # @param db_server_key character  (optional)
  # @param db_server_url character  (optional)
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreateRecordInstancesInstanceIdModulesModuleNameModelNamePut", {
  # tests for CreateRecordInstancesInstanceIdModulesModuleNameModelNamePut
  # base path: http://localhost
  # Create Record
  # @param instance_id character
  # @param module_name character
  # @param model_name character
  # @param schema_id character
  # @param body AnyType
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteCollaboratorInstancesInstanceIdCollaboratorsAccountIdDelete", {
  # tests for DeleteCollaboratorInstancesInstanceIdCollaboratorsAccountIdDelete
  # base path: http://localhost
  # Delete Collaborator
  # @param instance_id character
  # @param account_id character
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteInstanceInstancesInstanceIdDelete", {
  # tests for DeleteInstanceInstancesInstanceIdDelete
  # base path: http://localhost
  # Delete Instance
  # @param instance_id character
  # @param instance_name character
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteRecordInstancesInstanceIdModulesModuleNameModelNameUidDelete", {
  # tests for DeleteRecordInstancesInstanceIdModulesModuleNameModelNameUidDelete
  # base path: http://localhost
  # Delete Record
  # @param instance_id character
  # @param module_name character
  # @param model_name character
  # @param uid character
  # @param schema_id character
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("GeneratePasswordInstancesInstanceIdDbPasswordGet", {
  # tests for GeneratePasswordInstancesInstanceIdDbPasswordGet
  # base path: http://localhost
  # Generate Password
  # @param instance_id character
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("GenerateUrlInstancesInstanceIdDbUrlGet", {
  # tests for GenerateUrlInstancesInstanceIdDbUrlGet
  # base path: http://localhost
  # Generate Url
  # @param instance_id character
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetInstanceStatisticsInstancesInstanceIdStatisticsGet", {
  # tests for GetInstanceStatisticsInstancesInstanceIdStatisticsGet
  # base path: http://localhost
  # Get Instance Statistics
  # @param instance_id character
  # @param schema_id character
  # @param q array[character] In ${module}.${model} format (case-sensitive) (optional)
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetNonEmptyTablesInstancesInstanceIdNonEmptyTablesGet", {
  # tests for GetNonEmptyTablesInstancesInstanceIdNonEmptyTablesGet
  # base path: http://localhost
  # Get Non Empty Tables
  # @param instance_id character
  # @param schema_id character
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRecordInstancesInstanceIdModulesModuleNameModelNameIdOrUidPost", {
  # tests for GetRecordInstancesInstanceIdModulesModuleNameModelNameIdOrUidPost
  # base path: http://localhost
  # Get Record
  # @param instance_id character
  # @param module_name character
  # @param model_name character
  # @param id_or_uid character
  # @param schema_id character
  # @param limit_to_many integer  (optional)
  # @param include_foreign_keys character  (optional)
  # @param authorization character  (optional)
  # @param get_record_request_body GetRecordRequestBody  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRecordsInstancesInstanceIdModulesModuleNameModelNamePost", {
  # tests for GetRecordsInstancesInstanceIdModulesModuleNameModelNamePost
  # base path: http://localhost
  # Get Records
  # @param instance_id character
  # @param module_name character
  # @param model_name character
  # @param schema_id character
  # @param limit integer  (optional)
  # @param offset integer  (optional)
  # @param limit_to_many integer  (optional)
  # @param include_foreign_keys character  (optional)
  # @param authorization character  (optional)
  # @param get_records_request_body GetRecordsRequestBody  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRelationsInstancesInstanceIdSchemaModuleNameModelNameGet", {
  # tests for GetRelationsInstancesInstanceIdSchemaModuleNameModelNameGet
  # base path: http://localhost
  # Get Relations
  # @param module_name character
  # @param model_name character
  # @param instance_id character
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetSchemaInstancesInstanceIdSchemaGet", {
  # tests for GetSchemaInstancesInstanceIdSchemaGet
  # base path: http://localhost
  # Get Schema
  # @param instance_id character
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetValuesInstancesInstanceIdModulesModuleNameModelNameFieldsFieldPathPost", {
  # tests for GetValuesInstancesInstanceIdModulesModuleNameModelNameFieldsFieldPathPost
  # base path: http://localhost
  # Get Values
  # @param instance_id character
  # @param module_name character
  # @param model_name character
  # @param field_path character
  # @param schema_id character
  # @param limit integer  (optional)
  # @param offset integer  (optional)
  # @param authorization character  (optional)
  # @param get_values_request_body GetValuesRequestBody  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("GrantS3PermissionsStoragesS3BucketNamePermissionsPut", {
  # tests for GrantS3PermissionsStoragesS3BucketNamePermissionsPut
  # base path: http://localhost
  # Grant S3 Permissions
  # @param bucket_name character
  # @param s3_permissions_request S3PermissionsRequest
  # @param aws_account_id character  (optional)
  # @param aws_user_name character  (optional)
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("GroupByInstancesInstanceIdModulesModuleNameModelNameGroupByPost", {
  # tests for GroupByInstancesInstanceIdModulesModuleNameModelNameGroupByPost
  # base path: http://localhost
  # Group By
  # @param instance_id character
  # @param module_name character
  # @param model_name character
  # @param schema_id character
  # @param group_by_request_body GroupByRequestBody
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("TransferOwnershipInstancesInstanceIdOwnerHandlePatch", {
  # tests for TransferOwnershipInstancesInstanceIdOwnerHandlePatch
  # base path: http://localhost
  # Transfer Ownership
  # @param instance_id character
  # @param handle character
  # @param schema_id character
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateCollaboratorInstancesInstanceIdCollaboratorsAccountIdPatch", {
  # tests for UpdateCollaboratorInstancesInstanceIdCollaboratorsAccountIdPatch
  # base path: http://localhost
  # Update Collaborator
  # @param instance_id character
  # @param account_id character
  # @param role character
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateRecordInstancesInstanceIdModulesModuleNameModelNameUidPatch", {
  # tests for UpdateRecordInstancesInstanceIdModulesModuleNameModelNameUidPatch
  # base path: http://localhost
  # Update Record
  # @param instance_id character
  # @param module_name character
  # @param model_name character
  # @param uid character
  # @param schema_id character
  # @param body AnyType
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})
