# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Dimension")

model_instance <- Dimension$new()

test_that("field_name", {
  # tests for the property `field_name` (character)

  # uncomment below to test the property
  # expect_equal(model.instance$`field_name`, "EXPECTED_RESULT")
})

test_that("func", {
  # tests for the property `func` (character)

  # uncomment below to test the property
  # expect_equal(model.instance$`func`, "EXPECTED_RESULT")
})
