# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GroupByRequestBody")

model_instance <- GroupByRequestBody$new()

test_that("dimensions", {
  # tests for the property `dimensions` (array[Dimension])

  # uncomment below to test the property
  # expect_equal(model.instance$`dimensions`, "EXPECTED_RESULT")
})

test_that("measures", {
  # tests for the property `measures` (array[Measure])

  # uncomment below to test the property
  # expect_equal(model.instance$`measures`, "EXPECTED_RESULT")
})

test_that("filter", {
  # tests for the property `filter` (object)

  # uncomment below to test the property
  # expect_equal(model.instance$`filter`, "EXPECTED_RESULT")
})
