# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GetRecordRequestBody")

model_instance <- GetRecordRequestBody$new()

test_that("select", {
  # tests for the property `select` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`select`, "EXPECTED_RESULT")
})
