# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DefaultApi")

api_instance <- DefaultApi$new()

test_that("AddCollaboratorPut", {
  # tests for AddCollaboratorPut
  # base path: http://localhost
  # Add Collaborator
  # @param instance_id character
  # @param account_id character
  # @param schema_id character
  # @param role character  (optional)
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreateInstanceInstancesPut", {
  # tests for CreateInstanceInstancesPut
  # base path: http://localhost
  # Create Instance
  # @param name character
  # @param storage character  (optional)
  # @param schema_str character  (optional)
  # @param db_server_key character  (optional)
  # @param db_server_url character  (optional)
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreateRecordPut", {
  # tests for CreateRecordPut
  # base path: http://localhost
  # Create Record
  # @param instance_id character
  # @param module_name character
  # @param model_name character
  # @param schema_id character
  # @param body AnyType
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteCollaboratorDelete", {
  # tests for DeleteCollaboratorDelete
  # base path: http://localhost
  # Delete Collaborator
  # @param instance_id character
  # @param account_id character
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteInstanceDelete", {
  # tests for DeleteInstanceDelete
  # base path: http://localhost
  # Delete Instance
  # @param instance_id character
  # @param instance_name character
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteRecordDelete", {
  # tests for DeleteRecordDelete
  # base path: http://localhost
  # Delete Record
  # @param instance_id character
  # @param module_name character
  # @param model_name character
  # @param uid character
  # @param schema_id character
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("GeneratePasswordGet", {
  # tests for GeneratePasswordGet
  # base path: http://localhost
  # Generate Password
  # @param instance_id character
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("GenerateUrlGet", {
  # tests for GenerateUrlGet
  # base path: http://localhost
  # Generate Url
  # @param instance_id character
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetInstanceStatisticsGet", {
  # tests for GetInstanceStatisticsGet
  # base path: http://localhost
  # Get Instance Statistics
  # @param instance_id character
  # @param schema_id character
  # @param q array[character] In ${module}.${model} format (case-sensitive) (optional)
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetNonEmptyTablesGet", {
  # tests for GetNonEmptyTablesGet
  # base path: http://localhost
  # Get Non Empty Tables
  # @param instance_id character
  # @param schema_id character
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRecordPost", {
  # tests for GetRecordPost
  # base path: http://localhost
  # Get Record
  # @param instance_id character
  # @param module_name character
  # @param model_name character
  # @param id_or_uid character
  # @param schema_id character
  # @param limit_to_many integer  (optional)
  # @param include_foreign_keys character  (optional)
  # @param authorization character  (optional)
  # @param get_record_request_body GetRecordRequestBody  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRecordsPost", {
  # tests for GetRecordsPost
  # base path: http://localhost
  # Get Records
  # @param instance_id character
  # @param module_name character
  # @param model_name character
  # @param schema_id character
  # @param limit integer  (optional)
  # @param offset integer  (optional)
  # @param limit_to_many integer  (optional)
  # @param include_foreign_keys character  (optional)
  # @param authorization character  (optional)
  # @param get_records_request_body GetRecordsRequestBody  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRelationsGet", {
  # tests for GetRelationsGet
  # base path: http://localhost
  # Get Relations
  # @param module_name character
  # @param model_name character
  # @param instance_id character
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetSchemaGet", {
  # tests for GetSchemaGet
  # base path: http://localhost
  # Get Schema
  # @param instance_id character
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetValuesPost", {
  # tests for GetValuesPost
  # base path: http://localhost
  # Get Values
  # @param instance_id character
  # @param module_name character
  # @param model_name character
  # @param field_path character
  # @param schema_id character
  # @param limit integer  (optional)
  # @param offset integer  (optional)
  # @param authorization character  (optional)
  # @param get_values_request_body GetValuesRequestBody  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("GrantS3PermissionsPut", {
  # tests for GrantS3PermissionsPut
  # base path: http://localhost
  # Grant S3 Permissions
  # @param bucket_name character
  # @param s3_permissions_request S3PermissionsRequest
  # @param aws_account_id character  (optional)
  # @param aws_user_name character  (optional)
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("GroupByPost", {
  # tests for GroupByPost
  # base path: http://localhost
  # Group By
  # @param instance_id character
  # @param module_name character
  # @param model_name character
  # @param schema_id character
  # @param group_by_request_body GroupByRequestBody
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("TransferOwnershipPatch", {
  # tests for TransferOwnershipPatch
  # base path: http://localhost
  # Transfer Ownership
  # @param instance_id character
  # @param handle character
  # @param schema_id character
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateCollaboratorPatch", {
  # tests for UpdateCollaboratorPatch
  # base path: http://localhost
  # Update Collaborator
  # @param instance_id character
  # @param account_id character
  # @param role character
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateRecordPatch", {
  # tests for UpdateRecordPatch
  # base path: http://localhost
  # Update Record
  # @param instance_id character
  # @param module_name character
  # @param model_name character
  # @param uid character
  # @param schema_id character
  # @param body AnyType
  # @param authorization character  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})
